import type { Metadata } from "next";

import "./globals.css";
import QueryProvider from "@/components/layout/QueryProvider";
import { Toaster } from "react-hot-toast";
import { Inter, Fira_Code } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JobBit",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // or .png, .svg, etc.
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${firaCode.variable} antialiased`}>
        <QueryProvider>
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
